In [20]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Activation, Convolution2D, Flatten, MaxPooling2D, Dropout
from keras.utils import np_utils
from keras.layers.normalization import BatchNormalization
import os
import cv2
from sklearn.model_selection import train_test_split

In [2]:
dataset_path = './data/'

In [3]:
exp_data = []
labels = []
class_id = 0

In [4]:
data_x = []
data_y = []

In [5]:
ctr=0
for exp_name in os.listdir(dataset_path):
    label = ctr
    print(exp_name)
    if exp_name[0]!='.':
        photos = os.listdir(dataset_path+exp_name)
        for pic in photos:
#             print(pic)
            img = cv2.imread(dataset_path+exp_name+"/"+pic)
            data_x.append(img)
            data_y.append(label)
        ctr+=1

.DS_Store
kiss
glass
angry
smile


In [6]:
data_x=np.array(data_x)
data_y=np.array(data_y)
data_x = data_x/255.0
print(data_x.shape)
print(data_y.shape)

(3960, 100, 100, 3)
(3960,)


In [7]:
print(data_y)
print(np.unique(data_y))

[0 0 0 ... 3 3 3]
[0 1 2 3]


In [8]:
data_y = np.array(data_y)
print(np.unique(data_y))

[0 1 2 3]


In [9]:
print(np.unique(data_y))
data_y = np_utils.to_categorical(data_y)

[0 1 2 3]


In [10]:
print(data_y)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [21]:
x_train,x_test,y_train,y_test = train_test_split(data_x,data_y,test_size=0.2)

In [22]:
model = Sequential()

model.add(Convolution2D(64, kernel_size=(3, 3), input_shape=(100, 100, 3)))
model.add(Activation('relu'))
model.add(BatchNormalization(axis=1))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add( Dropout(0.2) )
model.add(Convolution2D(128, kernel_size=(3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization(axis=1))
model.add(Convolution2D(64, kernel_size=(4, 4)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization(axis=1))
model.add( Dropout(0.2) )
model.add(Flatten())
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dense(4))
model.add(Activation('softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_10 (Conv2D)           (None, 98, 98, 64)        1792      
_________________________________________________________________
activation_16 (Activation)   (None, 98, 98, 64)        0         
_________________________________________________________________
batch_normalization_10 (Batc (None, 98, 98, 64)        392       
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 49, 49, 64)        0         
_________________________________________________________________
dropout_7 (Dropout)          (None, 49, 49, 64)        0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 47, 47, 128)       73856     
_________________________________________________________________
activation_17 (Activation)   (None, 47, 47, 128)       0         
__________

In [23]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [24]:
model.fit(x_train, y_train, validation_data=( x_test, y_test ), epochs=5, batch_size=50)

Train on 3168 samples, validate on 792 samples
Epoch 1/5
3168/3168 [==============================] - 716s 226ms/step - loss: 0.8950 - acc: 0.8520 - val_loss: 0.0413 - val_acc: 0.9962
Epoch 2/5
3168/3168 [==============================] - 740s 234ms/step - loss: 0.0237 - acc: 0.9934 - val_loss: 0.0383 - val_acc: 0.9949
Epoch 3/5
3168/3168 [==============================] - 785s 248ms/step - loss: 0.0248 - acc: 0.9934 - val_loss: 0.2839 - val_acc: 0.8977
Epoch 4/5
3168/3168 [==============================] - 741s 234ms/step - loss: 0.0216 - acc: 0.9956 - val_loss: 0.0559 - val_acc: 0.9836
Epoch 5/5
3168/3168 [==============================] - 705s 223ms/step - loss: 0.0078 - acc: 0.9981 - val_loss: 0.0142 - val_acc: 0.9949


In [25]:
model.save('./Face_Gesture_Recogizer_Final.h5')