In [0]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Activation, Convolution2D, Flatten, MaxPooling2D, Dropout
from keras.utils import np_utils
from keras.layers.normalization import BatchNormalization
import os
import cv2

In [21]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 3302547063052147449, name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 11281553818
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 16379858240664317054
 physical_device_desc: "device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7"]

Import Dataset

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [23]:
!ls "/content/drive/My Drive"

 10.pdf				    'GRE BOOKS'
 12.pdf				    'GRE FULL'
'Academic Calendar_2016.pdf'	    'IOSD Marksheet.xlsx'
'ADA Assignment.pdf'		    'itihaas qiz final.pptx'
 app-debug.apk			    'm&slaw.pdf'
'Bootcamp July 2017'		    'Naive Bayes'
 buildAndroid.apk		     ntse.rar
 Calculator.gif			    'portal stuff.zip'
'Colab Notebooks'		    'pranav proj'
 CurvedLine-2017.1.2.unitypackage   'Project proposal.gdoc'
 cv-intern.pdf			    'Resume (1).gdoc'
'CV_SID LATHER_Final 25112014.rtf'  'Resume (2).gdoc'
 CV_TnP.pdf			    'Resume (3).gdoc'
 CV_TnP.pdf.gdoc		     Resume.gdoc
 driving_sim.apk		     spotify-8-4-5-1092.apk
'Eco Project 1.gdoc'		    'tanishq gym.mp4'
 EmojiData			    'Untitled document.gdoc'
 Face_Gesture_Recogizer_Final.h5    'vmc cd.zip'
 Face_Gesture_Recogizer.h5	    'Your Resume.pdf'
'Fruit Ninja Resources'


In [24]:
!ls "/content/drive/My Drive/EmojiData"

angry  glass  kiss  smile


In [0]:
dataset_path = '/content/drive/My Drive/EmojiData/'

In [0]:
exp_data = []
labels = []
class_id = 0

In [0]:
data_x = []
data_y = []

In [28]:
ctr=0
for exp_name in os.listdir(dataset_path):
    label = ctr
    print(exp_name)
    if exp_name[0]!='.':
        photos = os.listdir(dataset_path+exp_name)
        for pic in photos:
#             print(pic)
            img = cv2.imread(dataset_path+exp_name+"/"+pic)
            data_x.append(img)
            data_y.append(label)
        ctr+=1

smile
angry
glass
kiss


In [29]:
data_x=np.array(data_x)
data_y=np.array(data_y)
data_x = data_x/255.0
print(data_x.shape)
print(data_y.shape)

(3960, 100, 100, 3)
(3960,)


In [30]:
print(data_y)
print(np.unique(data_y))

[0 0 0 ... 3 3 3]
[0 1 2 3]


In [31]:
data_y = np.array(data_y)
print(np.unique(data_y))

[0 1 2 3]


In [32]:
print(np.unique(data_y))
data_y = np_utils.to_categorical(data_y)

[0 1 2 3]


In [33]:
print(data_y)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [34]:
model = Sequential()

model.add(Convolution2D(64, kernel_size=(3, 3), input_shape=(100, 100, 3)))
model.add(Activation('relu'))
BatchNormalization(axis=1)
model.add(MaxPooling2D(pool_size=(2,2)))
model.add( Dropout(0.2) )
model.add(Convolution2D(128, kernel_size=(3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
BatchNormalization(axis=1)
model.add(Convolution2D(512, kernel_size=(4, 4)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
BatchNormalization(axis=1)
model.add( Dropout(0.2) )
model.add(Flatten())
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dense(4))
model.add(Activation('softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 98, 98, 64)        1792      
_________________________________________________________________
activation_6 (Activation)    (None, 98, 98, 64)        0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 49, 49, 64)        0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 49, 49, 64)        0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 47, 47, 128)       73856     
_________________________________________________________________
activation_7 (Activation)    (None, 47, 47, 128)       0         
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 23, 23, 128)       0         
__________

In [0]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [36]:
model.fit(data_x, data_y, epochs=5, batch_size=50)

Epoch 1/5
3960/3960 [==============================] - 11s 3ms/step - loss: 0.4322 - acc: 0.8447
Epoch 2/5
3960/3960 [==============================] - 10s 3ms/step - loss: 0.0190 - acc: 0.9949
Epoch 3/5
3960/3960 [==============================] - 10s 3ms/step - loss: 0.0106 - acc: 0.9975
Epoch 4/5
3960/3960 [==============================] - 10s 3ms/step - loss: 0.0058 - acc: 0.9975
Epoch 5/5
3960/3960 [==============================] - 10s 3ms/step - loss: 0.0161 - acc: 0.9942


In [0]:
model.save('/content/drive/My Drive/Face_Gesture_Recogizer_Final_1.h5')